site_name: ASF Plugin Docs
theme:
  name: material
  highlightjs: true
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到白色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到黑暗主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 自适应主题
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  language: zh
  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.footer
    - navigation.path
    - navigation.indexes
    - search.suggest
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
plugins:
  - search
  - tags
dev_addr: 0.0.0.0:8000
nav:
  - index.md

  - Drones System:
      - Tcp 协议:
          - dronesSystem/tcp/index.md
          - dronesSystem/tcp/changelog.md
      - Ws 协议:
          - dronesSystem/ws/index.md
          - dronesSystem/ws/changelog.md
      - Http 协议:
          - dronesSystem/http/index.md
          - dronesSystem/http/changelog.md

  - 调试仪:
      - dtu/tsy_protocol.md
      - dtu/jdq_protocol.md
      - dtu/net_protocol.md

copyright: Copyright &copy; 2019 - 2024 赋兴（浙江）数字科技 Ltd.

extra:
  social:
    - icon: fontawesome/solid/link
      link: https://fusionxai.cn/
      name: 赋兴（浙江）数字科技

    - icon: fontawesome/solid/link
      link: https://fusionxai.com/
      name: 赋兴（浙江）数字科技

    - icon: fontawesome/solid/link
      link: https://fusionx.ai/
      name: 赋兴（浙江）数字科技
