name: Update READMEs from Private Repos

on:
  schedule:
    - cron: '0 0 * * *' # 每小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  update-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute download-docs.ps1
        run: pwsh download-docs.ps1

      - name: Execute generator-index.ps1
        run: pwsh generator-index.ps1

      - name: Check for changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Update documentation" && git push