name: Update READMEs from Private Repos

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Readme Files From RepoList
        shell: pwsh
        run: |
          . .\download-docs.ps1

          $Token = "${{ secrets.GH_TOKEN }}"
          $RepoFileName = "RepoNameList.txt"
          $Proxy = $null
          $DocsDir = "docs"

          if (-not (Test-Path $RepoFileName)) {
              Write-Error "File $RepoFileName not found!!!"
              exit 1
          }
          $userName = Get-GitHubUserName -token $Token -proxy $Proxy
          if (-not $userName) {
              Write-Error "Can not get GitHub username!!!"
              exit 1
          }
          $repoList = Get-RepoListFromFile -filePath $RepoFileName -userName $userName
          foreach ($repo in $repoList) {
              Write-Host "Processing: $repo"
              Get-GitHubRepoReadmes -token $Token -repoFullName $repo -proxy $Proxy
              Move-ReadmesToDocs -repoFullName $repo -docsDir $DocsDir
          }

          Update-MarkdownIndex -DocsDir $DocsDir

      - name: Check for changes
        shell: pwsh
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          if (git diff --cached --quiet) {
            Write-Host "No changes to commit."
          } else {
            git commit -m "Update documentation"
            $repo = "${{ github.repository }}"
            $branch = "${{ github.ref_name }}"
            $token = "${{ secrets.GH_TOKEN }}"
            git push "https://x-access-token:$token@github.com/$repo.git" HEAD:$branch
          }